export enum NotificationMessages {
    'BOOKING_ADDED' = 'You got a new booking from {student_name}. Please visit my booking to accept or decline it.',
    'BOOKING_INVITATION' = 'You have been invited to a booking from {student_name}. Please visit my booking to view details.',
    'BOOKING_ACCEPTED' = 'Your booking with {tutor_name} has been accepted. Please visit my bookings to complete the payment.',
    'BOOKING_REJECTED' = 'Your booking with {tutor_name} has been rejected. Please visit my bookings to view details.',
    'BOOKING_CANCELLED_TUTOR' = 'Your booking with {student_name} has been cancelled by student.',
    'BOOKING_CANCELLED_STUDENT' = 'Your booking with {tutor_name} has been cancelled by tutor.',
    'PAYMENT_SUCCESSFUL' = 'Your payment has been successful for the booking with {tutor_name}, Please visit my bookings to view details.',
    'PAYMENT_FAILED' = 'Your payment has been failed for the booking with {tutor_name}, Please visit my bookings to retry.',
    'ASSIGNMENT_ADDED' = 'New Assignment has been assigned to you by {tutor_name}. Please visit my assignment to view details.',
    'SUBMISSION_ADDED' = '{student_name} has added submission for assignment. Please visit my assignment to view details.',
    'NOTIFY_BOOKING_STUDENT' = 'Your booking with the {tutor_name} is going to start in 10 mins.',
    'NOTIFY_BOOKING_TUTOR' = 'Your booking with the {student_name} is going to start in 10 mins.',
    'PROFILE_APPROVED' = 'Your profile has been approved by Admin. Please visit my slots to open your slots to start getting bookings,',
    'PROFILE_REJECTED' = 'Your profile has been rejected by Admin. Please visit my profile for more details.',
    'MESSAGE_NOTIFICATION' = 'You had a unread message from {user_name}. Please visit chat to reply.',
    'INACTIVE' = 'Your profile has been marked as inactive. Please contact admin.',
}

export enum NotificationTitles {
    'BOOKING_ADDED' = 'New Booking',
    'BOOKING_INVITATION' = 'Booking Invitation',
    'BOOKING_ACCEPTED' = 'Booking Accepted',
    'BOOKING_REJECTED' = 'Booking Rejected',
    'BOOKING_CANCELLED_TUTOR' = 'Booking cancelled by student',
    'BOOKING_CANCELLED_STUDENT' = 'Booking cancelled by tutor',
    'PAYMENT_SUCCESSFUL' = 'Payment successful',
    'PAYMENT_FAILED' = 'Payment Failed',
    'ASSIGNMENT_ADDED' = 'New Assignment',
    'SUBMISSION_ADDED' = 'New Submission',
    'NOTIFY_BOOKING_STUDENT' = 'Upcoming Booking',
    'NOTIFY_BOOKING_TUTOR' = 'Upcoming Booking',
    'PROFILE_APPROVED' = 'Profile Approved',
    'PROFILE_REJECTED' = 'Profile Rejected',
    'MESSAGE_NOTIFICATION' = 'Unread Message',
    'INACTIVE' = 'Inactive',
}

export enum NotificationTypes {
    'BOOKING_ADDED' = 1,
    'BOOKING_INVITATION' = 2,
    'BOOKING_ACCEPTED' = 3,
    'BOOKING_REJECTED' = 4,
    'BOOKING_CANCELLED_TUTOR' = 5,
    'BOOKING_CANCELLED_STUDENT' = 6,
    'PAYMENT_SUCCESSFUL' = 7,
    'PAYMENT_FAILED' = 8,
    'ASSIGNMENT_ADDED' = 9,
    'SUBMISSION_ADDED' = 10,
    'NOTIFY_BOOKING_STUDENT' = 11,
    'NOTIFY_BOOKING_TUTOR' = 12,
    'PROFILE_APPROVED' = 13,
    'PROFILE_REJECTED' = 14,
    'MESSAGE_NOTIFICATION' = 15,
    'INACTIVE' = 16,
}

export enum EmailTypes {
    'BOOKING_ACCEPTED' = 'booking_accepted',
    'BOOKING_ADDED' = 'booking_created',
    'BOOKING_INVITATION' = 'booking_invitation',
    'PAYMENT_FAILED' = 'booking_payment_failed',
    'PAYMENT_SUCCESSFUL' = 'booking_payment_success',
    'BOOKING_REJECTED' = 'booking_rejected',
    'NOTIFY_BOOKING' = 'booking_remainder',
    'ASSIGNMENT_ADDED' = 'assignment_added',
    'PASSWORD_UPDATED' = 'password_change',
    'PROFILE_APPROVED' = 'profile_approved',
    'PROFILE_REJECTED' = 'profile_approved',
    'PROFILE_SUBMITTED' = 'profile_submitted',
    'RESET_PASSWORD' = 'reset_password_email',
    'SUBMISSION_ADDED' = 'submission_added',
    'VERIFY_EMAIL' = 'verify_email_otp',
    'WELCOME_EMAIL' = 'welcome_email',
}
